# Generated by Django 5.1 on 2024-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0003_alter_quote_text_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
